### ISSUE TITLE
libc_pyjac_test not built

### ISSUE THREAD

**Issue by DevinCharles** [Aalto-CFD/DLBFoam#17]
I haven't entirely tracked down what's happening here, but the build is failing because it can't link libc_pyjac_test.so. I find this in the build directory, but it's a symlink to itself. If I remove the symlink command in `runCmake.sh`, then it libc_pyjac_test.so does not exist.

**Comment by moreff** [comment]
Hi,

Can you please provide more details, the error message, or attach the log file? For the original code, without any modifications
