### ISSUE TITLE
OF9 version crashes when polynomial transport is used

### ISSUE THREAD

**Issue by moreff** [Aalto-CFD/DLBFoam#18]
In OpenFOAM 9, a dynamic compilation of thermo and chemistry was introduced and some of the combinations are not compiled in standard library. 
https://github.com/OpenFOAM/OpenFOAM-dev/commit/974712b2bdb05a1e2e736e61bca49a88cd08cda0

This leads to a crash when DLBFoam is used with e.g. polynomial transport:

```
--> FOAM FATAL IO ERROR:
Unknown solver type ode_pyJac
Supported solver types:
3
(
ode
none
EulerImplicit
)

file: /opt/openfoam9/etc/codeTemplates/dynamicCode/basicChemistryModel from line 17 to line 35.

    From function void Foam::compileTemplate::setFilterVariable(Foam::dynamicCode&, const Foam::dynamicCodeContext&, const Foam::Pair<Foam::word>&) const
    in file db/dynamicLibrary/compileTemplate/compileTemplate.C at line 81.

FOAM exiting
```

**Comment by blttkgl** [comment]
Out of curiosity, how does a user couple a given thermo and chemistry library now with the dynamic compilation? Do you just add the libraries you want to the controlDict and compile "dynamically"? If that is the case would that make the ode_pyJac available, or do you basically have to compile every combination on the standard library (which I guess defeats the purpose of this new feature) to make it happen?

**Comment by moreff** [comment]
Hi @blttkgl ,

Sorry for taking so long to respond.

There is of course an option to compile every possible combination, but I think we would like to avoid that and follow the way standard OF does it. I tried compilation of every combination I needed in DLBFoam as a temporary fix already and it works.

Another option is to enable dynamic compilation of DLBFoam with any combination of thermophysical properties.
I probably found a way to do it. 2 files from etc/codeTemplates need to be adjusted:
1. In [basicChemistryModel](https://github.com/OpenFOAM/OpenFOAM-9/blob/master/etc/codeTemplates/dynamicCode/basicChemistryModel) we need to include DLBFoam's `lnIclude`
2. In [basicChemistryModelTemplate.C](https://github.com/OpenFOAM/OpenFOAM-9/blob/master/etc/codeTemplates/dynamicCode/basicChemistryModelTemplate.C) we need to add an option to complile `LoadBalancedChemistryModel` and `pyJacLoadBalancedChemistryModel`

The most annoying problem here is that it will work only if the naming of the chemistry "solver" and "method" are consistent with the class names. Here we have a problem: 

- class `pyJacLoadBalancedChemistryModel` has `TypeName("loadBalanced_pyJac")`, which should be `TypeName("pyJacLoadBalanced")`
- class `LoadBalancedChemistryModel` has `TypeName("loadBalanced")`, which should be `TypeName("LoadBalanced")`

So, some renaming is required and users will need to change their `chemistryProperties` dictionaries for OF9 version after I will push the fixed version.

Anyway, I have a working solution locally already, I will resolve this issue soon hopefully.

**Comment by mahgadalla** [comment]
@moreff Just a quick question, how about renaming the classes to correspond to their TypeName strings, such that nothing changes wrt subdicts in the end-use. Would that actually work?
Of course, this way the naming convention will go off track a bit (i.e. uncapitalized initials + underscores) with regard to OF standards, but, perhaps this might help avoiding inconsistencies in the end-use!

**Comment by moreff** [comment]
Right, this will work, this is what I am doing already.
Thank you for the suggestion!
