### ISSUE TITLE
DLBFoam v1.1 for OpenFoam ESI version ?

### ISSUE THREAD

**Issue by kazumamatata** [Aalto-CFD/DLBFoam#19]
Hello!

Currently I am planning to use DLBFoam for my research.
However our supercomputer does only support the ESI version of OpenFoam (v2106).
Is there any version of DLBFoam v1.1 for v2106 or v2006  that can be shared?

If not, how much would be the work load to implement the support for v2106?

**Comment by mahgadalla** [comment]
Hi @kazumamatata 
Unfortunately, currently the publicly available DLBFoam version supporting ESI (v2006) only implements dynamic load balancing, i.e. without all features comprising pyJac+LAPACK coupling. 
If you would like to implement yourself, I may suggest to first implement the support for v2006 with pyJac and LAPACK. You may find it useful looking into the provided material in [this link](https://github.com/Aalto-CFD/CEMAFoam) regarding detailed instructions on coupling pyJac for v2006, although beware that ordering of solve vector (p,T,y) is therein different.
Then, for LAPACK, please track implementations in [this link](https://github.com/Aalto-CFD/DLBFoam/tree/main/src/ODE_DLB/ODESolvers/seulex_LAPACK) with respect to standard ODE implementation, and make sure to properly link the library in [Make](https://github.com/Aalto-CFD/DLBFoam/tree/main/src/ODE_DLB/Make).

**Comment by kazumamatata** [comment]
Thank you for your quick response.
The links might be very helpful for me!

Before I begin, I just want to ask, on your side there are no plans for implementing v1.1 for v2006 or other ESI versions?

**Comment by mahgadalla** [comment]
Regarding future support plans, my colleague @moreff will better answer you!

**Comment by moreff** [comment]
Hi @kazumamatata ,

Thank you for your message!
We were thinking about porting the v1.1 code to the ESI branch but it is not coming anytime soon, unfortunately.
Regarding workload, it is a tricky question, it can take up to several weeks I would say.

Also, consider installing/asking to install OpenFOAM 8/9 on the supercomputer.

**Comment by kazumamatata** [comment]
@moreff 
Thank you for your answer! 
For now I think I will use v1.0 for v2006
I was just told from the staff from supercomputer center, that OpenFOAM 8/9 doesn't support MPI memory optimization, so it could lead to full memory in a large scale calculation. That was my only concern
