### ISSUE TITLE
Proposing to drop EulerImplicit support

### ISSUE THREAD

**Issue by kahilah** [Aalto-CFD/DLBFoam#2]
At the moment we define `DLBEulerImplicitChemistrySolvers.C ` which is not really relevant from the practical use point of view. These parts could be dropped to simplify the code base.

**Comment by blttkgl** [comment]
That's a fair point. Only point it was originally included was because I was following the standard OpenFOAM templating. 

Fixed in commit 554e59d26253edc68b9e49704418609798bf6947
