### ISSUE TITLE
Integrating chemistry from old time properties

### ISSUE THREAD

**Issue by blttkgl** [Aalto-CFD/DLBFoam#27]
OpenFOAM v9 introduced a change in how chemistry is calculated, by not updating the thermophysical properties of the cell within the PIMPLE loop. Since the chemistry integration occurs within the simulation timestep, it should be initialised with old time properties. At the moment this is not the case. I attach the commit below and keep this issue active to be addressed later for v9 and v10 distributions.

https://github.com/OpenFOAM/OpenFOAM-9/commit/07adb183b4de0c14c352ff656abbf7773cee9e1d

**Comment by moreff** [comment]
Thank you for pointing this out!
Fixed for OF9 and OF10 branches
