### ISSUE TITLE
ECN case can not ignite when using ode coupled with only loadbalanced method 

### ISSUE THREAD

**Issue by minzhang0929** [Aalto-CFD/DLBFoam#28]
Hello, 

I run an ECN case using ode_pyJac solver with loadbalanced_pyjc method. This case works well.

However, when I change to ode solver with loadbalanced method,  the case did not show any chemistry iterations excluding C12H26, O2, CO2, and H2O. 

This is odd to me.

Do you know what the reason is? Looking forward to your help. 

thanks a lot

**Comment by moreff** [comment]
Hello,

Did you supply the kinetics mechanism in OpenFOAM format? 

With pyJac we use a separate dynamically linked library (`libc_pyjac.so`), which in fact contains this kinetics information and routines for Jacobian and derivative (dYdt) evaluation.
When you don't use pyJac, standard OpenFOAM chemistry method is used (the case of `loadbalanced`).
So for the mechanism, you need to supply the reactions dictionary in [this](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/tutorials/reactingFoam/shearlayer_DLB/constant/reactionsYao) format.

In our pyJac case setups, we use a placeholder for reactions: empty `reactions{}` dictionary (e.g. [here](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/tutorials/reactingFoam/shearlayer_DLB_pyJac/constant/chemistryProperties#L60)).
So when you switch from pyJac to standard method, you need to supply reactions dictionary

**Comment by minzhang0929** [comment]
> Hello,
> 
> Did you supply the kinetics mechanism in OpenFOAM format?
> 
> With pyJac we use a separate dynamically linked library (`libc_pyjac.so`), which in fact contains this kinetics information and routines for Jacobian and derivative (dYdt) evaluation. When you don't use pyJac, standard OpenFOAM chemistry method is used (the case of `loadbalanced`). So for the mechanism, you need to supply the reactions dictionary in [this](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/tutorials/reactingFoam/shearlayer_DLB/constant/reactionsYao) format.
> 
> In our pyJac case setups, we use a placeholder for reactions: empty `reactions{}` dictionary (e.g. [here](https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/tutorials/reactingFoam/shearlayer_DLB_pyJac/constant/chemistryProperties#L60)). So when you switch from pyJac to standard method, you need to supply reactions dictionary

Thanks a lot.
It works now.
