### ISSUE TITLE
Link tutorials to pre-compiled pyjac libraries

### ISSUE THREAD

**Issue by kahilah** [Aalto-CFD/DLBFoam#3]
At the moment user will be puzzled when he wants to run a pyjac tutorial and it's not possible without properly compiling and linking pyjac in the case folder. This is not desired. 

Utilise the pre-compiled mechanism in similar way as in e.g. testing class so the tutorial is directly runnable.

**Comment by blttkgl** [comment]
I am not so sure about this. In retrospect, the biggest issue new users face is generating and linking a mechanism succesfully. My 2₵ is we should integrate this process to the workflow up to succesfully running the tutorial so the user is familiar with how to do the linking. If we just automatically link the precompiled lib during compilation to the tutorial to avoid this, the user does not know how to use a mechanism apart from the one that is automatically linked.

**Comment by kahilah** [comment]
Whenever I face a new library or repository, the first thing what I want to do is to redo the references / tests or tutorials as such without learning too much of new things. I would drop a library if i can't run the first tutorial almost automatically...

We are anyway already compiling a test mech automatically so why not to use that directly one one tutorial. Would be soo much more clear for new users who just want to give a 5min test on this...We can make another tutorial about creating the mech + linking step by step. That's anyway for users who want to invest their time to the subject.
