### ISSUE TITLE
ISAT compatibility

### ISSUE THREAD

**Issue by blttkgl** [Aalto-CFD/DLBFoam#32]
I now have a branch on my fork where I extended ISAT to DLBFoam, and currently working on extending it to pyJac solvers: https://github.com/blttkgl/DLBFoam/tree/v1.1_OF10_ISAT

I am opening this issue to act as a placeholder, and let you know what we have under works for a near pull request.

Bulut

**Comment by moreff** [comment]
Functionality added in 0ac8b334aeff4d885c7fb01a4ea46dd5698c92e7 and 8b00125a0339a41c2d5b0e2b1d9e0fc97409507f
