### ISSUE TITLE
Solver crashed when using reduced mechanism

### ISSUE THREAD

**Issue by mactone** [Aalto-CFD/DLBFoam#33]
Note: if this is not a issue, please close it. 

I finally compiled the DLBFoam on Ubuntu with OpenFOAM9.
My case is runnable with GRI30 mechnism. 
I also tested Syngas/NOx (2017) mechanism (https://www.universityofgalway.ie/combustionchemistrycentre/mechanismdownloads/#)

However, when I using reduced mechanism (Azevedo mechanism as attached zip file) to run the same case, it crashed from the first step. [AZ.zip](https://github.com/Aalto-CFD/DLBFoam/files/9866340/AZ.zip)

On the contrary, running the case with Azevedo mechanism but not using ode_pyJac solver is okay.  That means the mechanism is acceptable on ode solver. I wonder where might go wrong with the reduced mechnism and ode_pyJac?

Thank you. 

Regards, 
Mactone

`Time scales min/max:
    Flow        = 1.57096767e-09, 1e-05
    Temperature = 4.49423284e+307, 4.49423284e+307
    Composition = 4.49423284e+307, 4.49423284e+307
    Overall     = 1.57096767e-09, 1e-05
Time = 25002

diagonal:  Solving for rho, Initial residual = 0, Final residual = 0, No Iterations 0
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#3  feraiseexcept in "/lib/x86_64-linux-gnu/libm.so.6"
#4  log in "/lib/x86_64-linux-gnu/libm.so.6"
#5  eval_rxn_rates at ??:?
#6  eval_jacob at ??:?
#7  Foam::loadBalanced_pyJacChemistryModel<Foam::sutherlandTransport<Foam::species::thermo<Foam::janafThermo<Foam::perfectGas<Foam::specie> >, Foam::sensibleEnthalpy> > >::jacobian(double, Foam::Field<double> const&, int, Foam::Field<double>&, Foam::SquareMatrix<double>&) const at ??:?
#8  Foam::seulex_LAPACK::solve(double&, Foam::Field<double>&, int, Foam::ODESolver::stepState&) const at ??:?
#9  Foam::ODESolver::solve(double, double, Foam::Field<double>&, int, double&) const at ??:?
#10  Foam::ode_pyJac<Foam::loadBalanced_pyJacChemistryModel<Foam::sutherlandTransport<Foam::species::thermo<Foam::janafThermo<Foam::perfectGas<Foam::specie> >, Foam::sensibleEnthalpy> > > >::solve(double&, double&, Foam::Field<double>&, int, double&, double&) const at ??:?
#11  Foam::loadBalancedChemistryModel<Foam::sutherlandTransport<Foam::species::thermo<Foam::janafThermo<Foam::perfectGas<Foam::specie> >, Foam::sensibleEnthalpy> > >::solveSingle(Foam::ChemistryProblem&, Foam::ChemistrySolution&) const at ??:?
#12 
[AZ.zip](https://github.com/Aalto-CFD/DLBFoam/files/9866340/AZ.zip)
 Foam::loadBalancedChemistryModel<Foam::sutherlandTransport<Foam::species::thermo<Foam::janafThermo<Foam::perfectGas<Foam::specie> >, Foam::sensibleEnthalpy> > >::solveList(Foam::UList<Foam::ChemistryProblem>&) const at ??:?
#13  double Foam::loadBalancedChemistryModel<Foam::sutherlandTransport<Foam::species::thermo<Foam::janafThermo<Foam::perfectGas<Foam::specie> >, Foam::sensibleEnthalpy> > >::solve<Foam::Field<double> >(Foam::Field<double> const&) at ??:?
#14  Foam::combustionModels::laminar::correct() at ??:?
#15  Foam::combustionModels::PaSR::correct() at ??:?
#16  ? in "/opt/openfoam9/platforms/linux64GccDPInt32Opt/bin/reactingFoam"
#17  ? in "/lib/x86_64-linux-gnu/libc.so.6"
#18  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
#19  ? in "/opt/openfoam9/platforms/linux64GccDPInt32Opt/bin/reactingFoam"`

**Comment by blttkgl** [comment]
Have you read and followed the mechanism generation part of the README? https://github.com/Aalto-CFD/DLBFoam#mechanism-generation  If you are using a new mechanism, you need to create its species and thermo files, as well as the dynamic pyjac library you link to your solver through controlDict, have you done that already?

**Comment by kahilah** [comment]
Have you generated and compiled the pyjac libraries for your mechanism according to the instructions?

Please provide a minimal case setup for easy testing.

**Comment by mactone** [comment]
> Have you generated and compiled the pyjac libraries for your mechanism according to the instructions?
> 
> Please provide a minimal case setup for easy testing.

Yes. I've generated and compiled the pyjac libraries as shown in my post attachment AZ.zip. 

Commands used as shown below, the grimech30 is just an example. When compiling AZ mechanism, I'll refer to the corresponding file. 

`
python -m cantera.ck2cti --input=grimech30.dat(or other mechanism data) --themo=thermo30.dat --transport=transport.dat

python -m pyjac --lang c --last_species N2 --input grimech30.cti

pyjac2foam.sh --mechanism grimech.cti --input out -- compile

`

I did the same procedure with GRI-MECH3.0, Syngas/NO, Azevedo mechanism. The former two run OK, only the last one crashed.

**Comment by blttkgl** [comment]
Interesting, I don't see any generated files from ct2foam inside your zip file. Can you provide a simple test case with the generated libraries? Even a copy of one of the tutorials with your mechanism should suffice.

**Comment by mactone** [comment]
> Interesting, I don't see any generated files from ct2foam inside your zip file. Can you provide a simple test case with the generated libraries? Even a copy of one of the tutorials with your mechanism should suffice.

I forgot to pack the sub folder into the zip file. 
Please use the new zip file. 
[AZ.zip](https://github.com/Aalto-CFD/DLBFoam/files/9866665/AZ.zip)

**Comment by mactone** [comment]
> Interesting, I don't see any generated files from ct2foam inside your zip file. Can you provide a simple test case with the generated libraries? Even a copy of one of the tutorials with your mechanism should suffice.

I use the compiled Azevedo mechanism on counterFlowFlame2D case. It run well. 

The issue I have is a start from the stable result from JL4 mechanism. I wonder if changing the mechanism is not permitted ?

**Comment by blttkgl** [comment]
Sorry I should've been more clear, can you provide an OpenFOAM case setup with the mechanism already linked, so I can run the solver and replicate the error message you are getting?

**Comment by blttkgl** [comment]
Wait, so are you saying that you run a simulation with one mechanism, then change the chemical mechanism, and continue the simulation? If that is the case, this is a practice where any number of things could be the culprit. 1) Are all the species in your first mechanism exists in your second mechanism? 2)Are you sure that you absolutely correct every single entry regarding chemical mechanism linking? This is not something  we intended users to do, although it should be possible if you are careful with above points.

**Comment by mactone** [comment]
> 

Yes. I run a simulation with one mechanism, then change the chemical mechanism afterwards. It's okay when I am not using pyJac. 

As you suggested, I've rerun my case from 0 step and start with the Azevedo mechnism with pyJac. The "crash from 'start'" issue is cleared. 

I think the issue is on me not on the DLBFoam.  Please forgive me for being stupid. 

It's not related to the "issue". May I ask how do you create the plot in the readme section? What I really want to know is how do I know the blance of calculation will accelerate my calculation on my case ?

![68747470733a2f2f692e696d6775722e636f6d2f795956426748562e676966](https://user-images.githubusercontent.com/44308384/197951847-f5f86894-ea35-42de-abb6-d30a43bc4550.gif)

**Comment by blttkgl** [comment]
It's all good. Good luck with your simulations.

Please check the solve_buffer.py python script in the tutorial folder. https://github.com/Aalto-CFD/DLBFoam/blob/v1.1_OF9/tutorials/reactingFoam/shearlayer_DLB_pyJac/solve_buffer.py
