### ISSUE TITLE
Catch2 version outdated

### ISSUE THREAD

**Issue by arintanen** [Aalto-CFD/DLBFoam#35]
Catch2 v2.9.2 and hence the unit tests don't compile with newer glibc versions, where MINSIGSTKSZ is not longer defined as a constant (more info at https://github.com/catchorg/Catch2/issues/2178). It is fixed since version v2.13.5 and the catch.hpp headerfile should be updated with a newer version. Defining it as a constant worked as a temporary fix for me.

Also some user modifications is required in ODE_DLB/Make/options.mkl file if MKL is installed from Ubuntu's repositories. By default, headers and libraries are installed into separate folders /usr/include/mkl and /usr/lib/x86_64-linux-gnu/mkl/, but the include and linking paths are defined as -L${MKLROOT}/lib/intel64/ and -I${MKLROOT}/include/ in the project.

**Comment by moreff** [comment]
Thank you for this comment! This issue was also discussed at #21 
I resolved it now in all v1.1 branches
