### ISSUE TITLE
Allwmake_Aalto fails compilation for Desktop platform

### ISSUE THREAD

**Issue by drhcelik** [Aalto-CFD/DLBFoam#6]
Hello! 

Allwmake_Aalto script doesn't compile the ODE_DLB library for the `DESKTOP` platform. 

This issue can be solved by changing line 41 of the Allwmake_Aalto script from

`cp src/ODE_DLB/Make/options.desktop src/ODE_DLB/Make/options`

to

`cp src/ODE_DLB/Make/options.standalone src/ODE_DLB/Make/options`

Thanks!

**Comment by moreff** [comment]
Hello,

Thank you, fixed now
